# Generated by Django 5.0 on 2024-01-11 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bebidas',
            old_name='tipo',
            new_name='marca',
        ),
        migrations.RenameField(
            model_name='comidas',
            old_name='tipo',
            new_name='marca',
        ),
    ]
