# Generated by Django 5.0 on 2024-01-11 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_rename_tipo_bebidas_marca_rename_tipo_comidas_marca'),
    ]

    operations = [
        migrations.CreateModel(
            name='BebidasSinAlcohol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('marca', models.CharField(max_length=60)),
                ('precio', models.IntegerField()),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Bebidas',
            new_name='BebidasConAlcohol',
        ),
    ]
